services:
  app:
    image: php:8.2-fpm
    container_name: gogowallet_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "docker-php-ext-install pdo pdo_mysql && php-fpm"

  db:
    image: mysql:8
    container_name: gogowallet_db
    restart: always
    environment:
      MYSQL_DATABASE: iae
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: